---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.8
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[dwarf_fortress::default]
    attributes:
 
